version: "3.7"

services:
  dropbox:
    image: janeczku/dropbox
    restart: unless-stopped
    environment:
      - DBOX_UID=1000
      - DBOX_GID=1001
    volumes:
      - ./dbox/.dropbox:/dbox/.dropbox
      - ./dbox/dropbox:/dbox/Dropbox
  pia:
    build: https://github.com/qdm12/private-internet-access-docker.git
    image: qmcgaw/private-internet-access
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: bridge
    init: true
    ports:
      - "8112:8112"
      - "5050:5050"
    environment:
      - ENCRYPTION=strong
      - PROTOCOL=udp
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/pia/forwarded_port
      - NONROOT=no
      - DOT=on
      - BLOCK_MALICIOUS=on
      - BLOCK_NSA=on
      - FIREWALL=on
      - TZ=America/New_York
    env_file:
      - ./.pia.env
    volumes:
      - pia:/pia
  deluge:
    image: linuxserver/deluge
    restart: unless-stopped
    network_mode: "service:pia"
    environment:
      - PUID=113
      - PGID=1001
      - UMASK_SET=002
      - TZ=America/New_York
    volumes:
      - ./deluge/config:/config
      - ./deluge/trigger-decompress.sh:/usr/local/bin/trigger-decompress.sh:ro
      - ./deluge/downloads:/downloads
      - /media/raid/videos:/videos
      - pia:/pia:ro
  flexget:
    image: cpoppema/docker-flexget:amd64-latest
    restart: unless-stopped
    environment:
      - PUID=112
      - PGID=1001
      - TZ=America/New_York
      - TORRENT_PLUGIN=deluge
      - FLEXGET_LOG_LEVEL=info
      - FLEXGET_SERIES_SHOW_SORTBY_FIELD=identifier
    volumes:
      - ./flexget:/config
      - ./flexget/99-install-other-deps:/etc/cont-init.d/99-install-other-deps:ro
      - ./dbox/dropbox/Flexget/db-config.sqlite:/config/db-config.sqlite
      - ./dbox/dropbox/torrents:/home/jawilson/Dropbox/torrents
      - ./dbox/dropbox/Flexget/secretfile.yml:/config/secretfile.yml:ro
      - ./deluge/downloads:/downloads:ro
      - /media/raid/videos:/videos

volumes:
  pia:
